// ui/src/react/components/header/Header.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useMemo, useRef } from 'react';
import { Link, NavLink } from 'react-router-dom';

// import logoDark from '../../../assets/icons/icon-72x72.png';
// import logoLight from '../../../assets/icons/icon-light-72x72.png';
import useTeam from '../../hooks/useTeam';
import useTheme from '../../hooks/useTheme';
import SaveCheckerService from '../../services/SaveCheckerService';
import Theme from '../../types/Theme';
import { ModalMethods } from '../modal/Modal';
import SettingsDialog from '../settings-dialog/SettingsDialog';

import './Header.scss';

type RqLink = {
  label: 'retro' | 'archives' | 'radiator';
  path: string;
};

const LINKS: RqLink[] = [
  { label: 'retro', path: '' },
  { label: 'archives', path: '/archives' },
  { label: 'radiator', path: '/radiator' },
];

interface Props {
  teamId?: string;
  routeTo?: (string) => void;
}

// @todo import images in react way when app is fully react
const darkLogoPath = '/assets/icons/icon-72x72.png';
const lightLogoPath = '/assets/icons/icon-light-72x72.png';

export default function Header(props: Props) {
  const { teamId, teamName } = useTeam();

  const [theme] = useTheme();

  const modalRef = useRef<ModalMethods>();

  const lastSavedText = useMemo(() => {
    if (SaveCheckerService.lastSavedDateTime === '') {
      return 'All changes saved';
    }
    return 'Last change saved at ' + SaveCheckerService.lastSavedDateTime;
  }, []);

  return (
    <>
      <header className="header">
        <div className="left-content">
          <a href="/" className="logo-link">
            <img
              src={theme === Theme.DARK ? lightLogoPath : darkLogoPath}
              className="logo"
              title="RetroQuest"
              alt="RetroQuest"
            />
          </a>
          <div className="horizontal-separator" />
          <div className="team-name">{teamName}</div>
        </div>
        <nav className="center-content">
          {/* @todo change to navlink once app is fully react */}
          {LINKS.map((link) => (
            <a
              key={link.path}
              // className={({ isActive }) => 'nav-link button' + (isActive ? ' activated' : '')}
              className="nav-link button"
              href={`/team/${teamId}${link.path}`}
              // end
            >
              {link.label}
            </a>
          ))}
        </nav>
        <div className="right-content">
          <div className="last-saved-text">{lastSavedText}</div>
          <button
            className="settings-button fas fa-cog"
            onClick={() => modalRef.current?.show()}
            data-testid="settingsButton"
          />
        </div>
      </header>
      <SettingsDialog ref={modalRef} />
    </>
  );
}

// ui/src/app/modules/teams/components/header/header.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output, ViewChild} from '@angular/core';
import {EndRetroDialogComponent} from '../../../controls/end-retro-dialog/end-retro-dialog.component';
import {FeedbackService} from '../../services/feedback.service';
import {Feedback} from '../../../domain/feedback';
import {FeedbackDialogComponent} from '../../../controls/feedback-dialog/feedback-dialog.component';
import {SaveCheckerService} from '../../services/save-checker.service';
import {Themes} from "../../../domain/Theme";

@Component({
  selector: 'rq-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  host: {
    '[class.dark-theme]': 'darkThemeIsEnabled'
  }
})
export class HeaderComponent {
  @Input() teamName: string;
  @Input() teamId: string;
  @Input() theme = Themes.Light;

  @Output() endRetro: EventEmitter<void> = new EventEmitter<void>();
  @Output() actionsRadiatorViewClicked: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Output() themeChanged: EventEmitter<Themes> = new EventEmitter<Themes>();

  @ViewChild(FeedbackDialogComponent) feedbackDialog: FeedbackDialogComponent;
  @ViewChild(EndRetroDialogComponent) endRetroDialog: EndRetroDialogComponent;

  actionsRadiatorViewEnabled = false;

  constructor(
    private feedbackService: FeedbackService,
    private saveChecker: SaveCheckerService
  ) {

  }

  get darkThemeIsEnabled(): boolean {
    return this.theme === Themes.Dark;
  }

  public getCsvUrl(): string {
    return `api/team/${this.teamId}/csv`;
  }

  public showEndRetroDialog(): void {
    this.endRetroDialog.show();
  }

  public onEndRetroDialogSubmitted(): void {
    this.endRetro.emit();
  }

  public onFeedbackSubmitted(feedback: Feedback) {
    feedback.teamId = this.teamId;
    this.feedbackService.addFeedback(feedback).subscribe();
  }

  public onActionsRadiatorViewClicked(): void {
    this.actionsRadiatorViewEnabled = !this.actionsRadiatorViewEnabled;
    this.actionsRadiatorViewClicked.emit(this.actionsRadiatorViewEnabled);
  }

  get lastSavedText(): string {
    if (this.saveChecker.lastSavedDateTime === '') {
      return 'All changes saved';
    }

    return 'Last change saved ' + this.saveChecker.lastSavedDateTime;
  }

  public toggleThemeColor(): void {

    if (this.theme === Themes.Dark) {
      this.theme = Themes.Light;
    } else {
      this.theme = Themes.Dark;
    }

    this.themeChanged.emit(this.theme);
  }
}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<header id="header">

  <rq-top-header [teamName]="teamName" [lastSavedText]="lastSavedText"></rq-top-header>

  <div id="headerBottom">
    <div
      class="header-bottom-content"
      [ngClass]="{
          'center-content': actionsRadiatorViewEnabled
      }"
    >

      <rq-button
        class="actions-radiator-button"
        type="secondary"
        [text]="actionsRadiatorViewEnabled ? 'view retro' : 'actions radiator'"
        (click)="onActionsRadiatorViewClicked()"
      ></rq-button>

      <button id="giveFeedback" class="rq-button-secondary" (click)="feedbackDialog.show()">
        <span class="button-text">Give Feedback</span>
        <i class="far fa-comments button-icon"></i>
      </button>

      <a routerLink="/team/{{teamId}}/archives">
        <button class="rq-button-secondary">
          <span class="button-text">Archives</span>
        </button>
      </a>

      <a id="downloadCsv"
         [href]="getCsvUrl()"
         [ngClass]="{
            'hide': actionsRadiatorViewEnabled
         }"
      >
        <button class="rq-button-secondary">
          <span class="button-text">Download CSV</span>
          <i class="fas fa-download button-icon"></i>
        </button>
      </a>

      <button
        id="endRetro"
        class="rq-button-primary"
        (click)="showEndRetroDialog()"
        [ngClass]="{
            'hide': actionsRadiatorViewEnabled
         }"
      >
        <span class="button-text">End Retro</span>
      </button>
    </div>
  </div>

</header>


<rq-feedback-dialog
  #feedbackDialog
  (submitted)="onFeedbackSubmitted($event)"
></rq-feedback-dialog>

<rq-end-retro-dialog
  #endRetroModal
  [visible]="false"
  (submitted)="onEndRetroDialogSubmitted()"
></rq-end-retro-dialog>
