// ui/src/App/Team/Header/SettingsDialog/SettingsDialog.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { forwardRef, Ref, useState } from 'react';
import classnames from 'classnames';

import Dialog from '../../../../Common/Dialog/Dialog';
import Modal, { ModalMethods } from '../../../../Common/Modal/Modal';

import AccountTab from './AccountTab/AccountTab';
import InfoTab from './InfoTab/InfoTab';
import StylesTab from './StylesTab/StylesTab';

import './SettingsDialog.scss';

function SettingsDialog(props: unknown, ref: Ref<ModalMethods>) {
	return (
		<Modal ref={ref}>
			<SettingsDialogContent />
		</Modal>
	);
}

enum Tabs {
	STYLES = 'styles',
	ACCOUNT = 'account',
	INFO = 'info',
}

export function SettingsDialogContent() {
	const [tab, setTab] = useState<Tabs>(Tabs.STYLES);

	const stylesTabIsActive = () => tab === Tabs.STYLES;
	const accountTabIsActive = () => tab === Tabs.ACCOUNT;
	const infoTabIsActive = () => tab === Tabs.INFO;

	return (
		<Dialog
			className="settings-dialog"
			title="Settings"
			subtitle="choose your preferences"
		>
			<div className="tab-container">
				<div className="tab-heading">
					<button
						className={classnames('tab', { selected: stylesTabIsActive() })}
						onClick={() => setTab(Tabs.STYLES)}
					>
						Styles
					</button>
					<button
						className={classnames('tab', { selected: accountTabIsActive() })}
						onClick={() => setTab(Tabs.ACCOUNT)}
					>
						Account
					</button>
					<button
						className={classnames('tab', { selected: infoTabIsActive() })}
						onClick={() => setTab(Tabs.INFO)}
					>
						Info
					</button>
				</div>
				{stylesTabIsActive() && <StylesTab />}
				{accountTabIsActive() && <AccountTab />}
				{infoTabIsActive() && <InfoTab />}
			</div>
		</Dialog>
	);
}

export default forwardRef<ModalMethods>(SettingsDialog);

// ui/src/app/modules/controls/settings-dialog/settings-dialog.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {AuthService} from '../../auth/auth.service';
import {Router} from '@angular/router';
import {Themes, themeToString} from '../../domain/Theme';

@Component({
  selector: 'rq-settings-dialog',
  templateUrl: './settings-dialog.component.html',
  styleUrls: ['./settings-dialog.component.scss'],
  host: {
    '(click)': 'hide()',
    '[style.display]': 'visible ? "flex": "none"'
  }
})
export class SettingsDialogComponent {

  @Input() visible = false;
  @Input() teamId: string;
  @Input() theme: Themes;
  @Output() themeChanged: EventEmitter<Themes> = new EventEmitter();

  _stylesTabIsVisible = true;
  _accountTabIsVisible = false;

  constructor(private router: Router) {
  }

  set stylesTabIsVisible(visible: boolean) {
    this._stylesTabIsVisible = visible;
    this.accountTabIsVisible = !visible;
  }

  get stylesTabIsVisible(): boolean {
    return this._stylesTabIsVisible;
  }

  set accountTabIsVisible(visible: boolean) {
    this._accountTabIsVisible = visible;
    this.stylesTabIsVisible = !visible;
  }

  get accountTabIsVisible(): boolean {
    return this._accountTabIsVisible;
  }

  show() {
    this.visible = true;
  }

  hide() {
    this.visible = false;
  }

  logoutOfAccount() {
    AuthService.clearToken();
    this.router.navigate(['login', this.teamId]);
  }

  enableDarkTheme() {
    this.enableTheme(Themes.Dark);
  }

  enableLightTheme() {
    this.enableTheme(Themes.Light);
  }

  private enableTheme(theme: Themes) {
    this.theme = theme;
    this.themeChanged.emit(this.theme);
    this.saveTheme();
  }

  get darkThemeIsEnabled(): boolean {
    return this.theme === Themes.Dark;
  }

  get lightThemeIsEnabled(): boolean {
    return this.theme === Themes.Light;
  }

  private saveTheme(): void {
    const themeString = themeToString(this.theme);
    if (themeString !== '') {
      localStorage.setItem('theme', themeString);
    }
    this.themeChanged.emit(this.theme);
  }

}

<!--
  ~  Copyright (c) 2020 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<div
  class="dialog"
  (click)="$event.stopPropagation()"
  [ngClass]="{
    'dark-theme': darkThemeIsEnabled
  }"
>
  <div class="heading-container">
    <div class="heading">settings</div>
    <div
      class="sub-heading"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    >choose your preferences <em>(Beta)</em>
    </div>
  </div>

  <div class="body">
    <div class="tab-heading">
      <div
        class="tab"
        (click)="stylesTabIsVisible = true"
        [ngClass]="{
          'selected': stylesTabIsVisible,
          'dark-theme': darkThemeIsEnabled
        }"
      >styles
      </div>
      <div
        class="tab"
        (click)="accountTabIsVisible = true"
        [ngClass]="{
          'selected': accountTabIsVisible,
          'dark-theme': darkThemeIsEnabled
        }"
      >account
      </div>
    </div>

    <div class="tab-body styles-tab-body" *ngIf="stylesTabIsVisible">
      <div class="label">appearance</div>
      <div class="tab-heading theme-tab-heading">

        <div class="theme-icon-container">
          <img
            src="./assets/light-theme-picture.jpg"
            [ngClass]="{
            'selected': lightThemeIsEnabled
          }"
            (click)="enableLightTheme()"
          />
          <div class="theme-icon-label">light</div>
        </div>

        <div class="theme-icon-container">

          <img
            src="./assets/dark-theme-picture.jpg"
            [ngClass]="{
            'selected': darkThemeIsEnabled
          }"
            (click)="enableDarkTheme()"
          />
          <div class="theme-icon-label">dark</div>

        </div>
      </div>

    </div>

    <div class="tab-body account-tab-body" *ngIf="accountTabIsVisible">
      <rq-button text="logout" type="primary" (click)="logoutOfAccount()"></rq-button>
    </div>

  </div>
</div>
