// ui/src/app/modules/teams/components/feedback-form/feedback-form.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, Input} from '@angular/core';
import {Feedback} from '../../domain/feedback';
import {FeedbackService} from '../../services/feedback.service';

@Component({
  selector: 'rq-feedback-form',
  templateUrl: './feedback-form.component.html',
  styleUrls: ['./feedback-form.component.scss']
})
export class FeedbackFormComponent {

  static emptyStar = 'star_border';
  static fullStar = 'star';

  @Input() teamId: string;

  maxStars = 5;
  rating = 0;
  stars: string[];
  comments = '';
  followupEmail = '';

  constructor (private feedbackService: FeedbackService) {
    this.stars = this.emptyStars();
  }

  emptyStars () {
    const emptyStars = [];
    for (let i = 0; i < this.maxStars; i++) {
      emptyStars.push(FeedbackFormComponent.emptyStar);
    }
    return emptyStars;
  }

  reset () {
    this.stars = this.emptyStars();
    this.rating = 0;
    this.comments = '';
    this.followupEmail = '';
  }

  setRating (rating: number) {
    this.rating = rating;
    this.stars = this.emptyStars();
    for (let i = 0; i < rating; i++) {
      this.stars[i] = FeedbackFormComponent.fullStar;
    }
  }

  submit () {
    if (this.comments && this.comments.length) {
      const feedback: Feedback = {
        stars: this.rating,
        comment: this.comments,
        userEmail: this.followupEmail,
        teamId: this.teamId
      };

      this.feedbackService.addFeedback(feedback).subscribe(
        (response) => {
          console.log(response);
        }
      );
    }
  }

}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="title">
  Please share your thoughts and impressions with us. We're always improving this tool and your feedback is
  appreciated.
</div>

<div class="rating">
      <span *ngFor="let star of stars.reverse(); let i = index"
            (click)="setRating(maxStars - i)">{{star}}</span>
</div>
<div>
  <label for="comments">Comments</label>
  <textarea id="comments" placeholder="Enter comments here" rows="5" [(ngModel)]="comments"></textarea>
</div>
<div>
  <label for="email">Email</label>
  <input id="email"
         placeholder="Enter email if you would like us to follow up"
         type="email"
         [(ngModel)]="followupEmail"/>
</div>

// ui/src/App/Team/Retro/RetroSubheader/FeedbackForm/FeedbackForm.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState } from 'react';
import { useRecoilValue, useSetRecoilState } from 'recoil';

import FormTemplate from '../../../../../Common/FormTemplate/FormTemplate';
import FeedbackService from '../../../../../Services/Api/FeedbackService';
import { ModalContentsState } from '../../../../../State/ModalContentsState';
import { TeamState } from '../../../../../State/TeamState';

import FeedbackStars from './FeedbackStars/FeedbackStars';

import './FeedbackForm.scss';

function FeedbackForm() {
	const setModalContents = useSetRecoilState(ModalContentsState);
	const team = useRecoilValue(TeamState);
	const [stars, setStars] = useState(0);
	const [comment, setComment] = useState<string>('');
	const [userEmail, setUserEmail] = useState<string>('');

	const closeModal = () => setModalContents(null);

	const onSubmit = () => {
		if (comment) {
			const feedback = {
				teamId: team.id,
				stars,
				comment,
				userEmail,
			};
			FeedbackService.addFeedback(feedback)
				.then(() => closeModal())
				.catch(console.error);
		}
	};

	return (
		<FormTemplate
			testId="feedbackForm"
			className="feedback-form"
			onSubmit={onSubmit}
			onCancel={closeModal}
			title="Feedback"
			subtitle="How can we improve RetroQuest?"
			cancelButtonText="Cancel"
			submitButtonText="Send!"
		>
			<FeedbackStars value={stars} onChange={setStars} />
			<div className="section comments-section">
				<label className="label" htmlFor="comments">
					Comments<span className="required-field">*</span>
				</label>
				<textarea
					className="comments-textarea"
					id="comments"
					value={comment}
					onChange={(event) => setComment(event.target.value)}
				/>
			</div>
			<div className="section feedback-email-section">
				<label className="label" htmlFor="email">
					Feedback Email
				</label>
				<input
					className="email-input"
					id="email"
					type="text"
					value={userEmail}
					onChange={(event) => setUserEmail(event.target.value)}
				/>
			</div>
		</FormTemplate>
	);
}

export default FeedbackForm;
