// ui/src/Common/ColumnHeader/ColumnHeader.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { HTMLAttributes, useEffect, useMemo, useState } from 'react';
import classNames from 'classnames';

import { emojify } from '../../Services/EmojiGenerator';
import Topic from '../../Types/Topic';
import { onEachKey } from '../../Utils/EventUtils';
import FloatingCharacterCountdown from '../FloatingCharacterCountdown/FloatingCharacterCountdown';
import Tooltip from '../Tooltip/Tooltip';

import './ColumnHeader.scss';

const maxTitleLength = 16;
const almostOutOfCharactersThreshold = 5;

interface ColumnHeaderProps extends HTMLAttributes<HTMLDivElement> {
	initialTitle?: string;
	type?: Topic;
	sortedChanged?: (changed: boolean) => void;
	titleChanged?: (title: string) => void;
}

function ColumnHeader(props: ColumnHeaderProps): JSX.Element {
	const {
		initialTitle = '',
		type = '',
		titleChanged,
		sortedChanged,
		...divProps
	} = props;
	const [title, setTitle] = useState(initialTitle);
	const [editedTitle, setEditedTitle] = useState(initialTitle);
	const sortable = useMemo(() => sortedChanged !== undefined, [sortedChanged]);
	const editable = useMemo(() => titleChanged !== undefined, [titleChanged]);
	const [editing, setEditing] = useState(false);
	const [sorted, setSorted] = useState(false);

	useEffect(() => setTitle(initialTitle), [initialTitle]);

	const updateTitle = (newTitle: string) => {
		setTitle(newTitle);
		setEditing(false);
		if (titleChanged) titleChanged(newTitle);
	};

	const handleBlur = () => {
		updateTitle(editedTitle);
	};

	const handleKeyDown = onEachKey({
		Enter: () => updateTitle(editedTitle),
		Escape: () => setEditing(false),
	});

	const toggleSort = () => {
		const newSorted = !sorted;
		setSorted(newSorted);
		if (sortedChanged) sortedChanged(newSorted);
	};

	const enableEditing = () => {
		setEditedTitle(title);
		setEditing(true);
	};

	const handleInputFocus = (event: any) => event.target.select();

	return (
		<div
			{...divProps}
			className={classNames('column-header', type)}
			data-testid={`columnHeader-${type}`}
		>
			{editing ? (
				<>
					<input
						type="text"
						className="column-input"
						data-testid="column-input"
						maxLength={maxTitleLength}
						value={editedTitle}
						onChange={(event) => setEditedTitle(event.target.value)}
						onBlur={handleBlur}
						onKeyDown={handleKeyDown}
						/* @todo fix this */
						/* eslint-disable-next-line jsx-a11y/no-autofocus */
						autoFocus={true}
						onFocus={handleInputFocus}
					/>
					<FloatingCharacterCountdown
						characterCount={editedTitle.length}
						maxCharacterCount={maxTitleLength}
						charsAreRunningOutThreshold={almostOutOfCharactersThreshold}
					/>
				</>
			) : (
				<>
					<p className="display-text">{emojify(title)}</p>
					{sortable && (
						<div className="sort-container">
							<div
								data-testid="columnHeader-sortButton"
								className={classNames(['fas', 'fa-sort-down', 'sort'], {
									'sort-icon-translucent': !sorted,
								})}
								onClick={toggleSort}
							/>
							<Tooltip>{sorted ? 'Unsort' : 'Sort'}</Tooltip>
						</div>
					)}
					{editable && (
						<span className={classNames(['edit-button'])}>
							<i
								className="fas fa-pencil-alt"
								onClick={enableEditing}
								aria-hidden="true"
								data-testid="columnHeader-editTitleButton"
							/>
							<Tooltip>Edit</Tooltip>
						</span>
					)}
				</>
			)}
		</div>
	);
}

export default ColumnHeader;

// ui/src/app/modules/components/column-header/column-header.component.ts
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ElementRef, EventEmitter, Input, OnInit, Output, ViewChild } from '@angular/core';

import { Column } from '../../domain/column';
import { Themes } from '../../domain/Theme';
import { emojify } from '../../utils/EmojiGenerator';

@Component({
  selector: 'rq-column-header',
  templateUrl: './column-header.component.html',
  styleUrls: ['./column-header.component.scss'],
  host: {
    '[class.happy]': "type === 'happy'",
    '[class.confused]': "type === 'confused'",
    '[class.sad]': "type === 'unhappy'",
    '[class.action]': "type === 'action'",
    '[class.dark-theme]': 'darkModeIsEnabled',
  },
})
export class ColumnHeaderComponent implements OnInit {
  @Input() title = '';
  @Input() type = '';

  @Input() column: Column;
  @Input() thoughtCount: number;

  @Input() readOnly = false;
  @Input() theme: Themes = Themes.Light;

  @Output() sortedChanged: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Output() titleChanged: EventEmitter<string> = new EventEmitter<string>();

  @ViewChild('inputField') inputFieldRef: ElementRef;

  titleCopy: string;
  readOnlyEnabled = true;
  sorted = false;
  maxTextLength = 16;
  escapeKeyPressed = false;
  myWindow: Window = window;

  public ngOnInit() {
    this.titleCopy = this.title.slice(0);
  }

  public get darkModeIsEnabled(): boolean {
    return this.theme === Themes.Dark;
  }

  public emitTitleChangedAndEnableReadonlyMode(): void {
    if (this.escapeKeyPressed) {
      this.escapeKeyPressed = false;
      this.titleCopy = '';
    } else {
      this.title = this.titleCopy.slice(0);
      this.titleChanged.emit(this.titleCopy);
    }

    this.readOnlyEnabled = true;
  }

  public toggleSort(): void {
    this.sorted = !this.sorted;
    this.sortedChanged.emit(this.sorted);
  }

  public toggleEdit(): void {
    this.readOnlyEnabled = false;
    this.focusInput();
  }

  private focusInput(): void {
    this.myWindow.setTimeout(() => {
      this.inputFieldRef.nativeElement.focus();
      this.inputFieldRef.nativeElement.select();
    }, 0);
  }

  public blurInput(): void {
    this.myWindow.setTimeout(() => {
      this.inputFieldRef.nativeElement.blur();
    }, 0);
  }

  public onEscapeKeyPressed(): void {
    this.escapeKeyPressed = true;
    this.blurInput();
  }

  public emojifyText(text: string): string {
    return emojify(text);
  }
}

<!--
  ~ Copyright (c) 2021 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<input
    #inputField
    data-testid="columnHeader-titleInput"
    [readonly]="readOnlyEnabled"
    [maxlength]="maxTextLength"
    [(ngModel)]="titleCopy"
    (blur)="emitTitleChangedAndEnableReadonlyMode()"
    (keydown.enter)="blurInput()"
    (keydown.escape)="onEscapeKeyPressed()"
    [ngClass]="{ hide: readOnlyEnabled }"
/>

<div class="display-text" [ngClass]="{ hide: !readOnlyEnabled }">
    {{ emojifyText(title) }}
</div>

<div class="sort-container">
    <div
        class="fas fa-sort-down sort"
        data-testid="columnHeader-sortButton"
        [ngClass]="{
            'sort-icon-translucent': !sorted,
            hide: !readOnlyEnabled
        }"
        (click)="toggleSort()"
    ></div>
    <rq-tooltip [theme]="theme" [text]="sorted ? 'Unsort' : 'Sort'"></rq-tooltip>
</div>

<span
    class="edit-button"
    [ngClass]="{
        'edit-button-enabled': !readOnlyEnabled || type === 'action'
    }"
    *ngIf="!readOnly"
>
    <i
        class="fas fa-pencil-alt"
        (click)="toggleEdit()"
        data-testid="columnHeader-editTitleButton"
        aria-hidden="true"
    ></i>

    <rq-tooltip [theme]="theme" text="Edit"></rq-tooltip>
</span>

<rq-floating-character-countdown
    [characterCount]="readOnlyEnabled ? 0 : titleCopy.length"
    [maxCharacterCount]="maxTextLength"
    [charsAreRunningOutThreshold]="5"
    [theme]="theme"
>
</rq-floating-character-countdown>
