// ui/src/react/components/settings-dialog/SettingsDialog.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';

import classnames from 'classnames';

import { PrimaryButton } from '../button/Button';
import './SettingsDialog.scss';

import lightThemeImage from '../../../assets/light-theme-picture.jpg';
import darkThemeImage from '../../../assets/dark-theme-picture.jpg';

type Theme = 'light-theme' | 'dark-theme';

type SettingsDialogProps = {
  theme: Theme;
  onThemeChange: (theme: Theme) => void;
  onLogout: () => void;
  onHide: () => void;
};

export type SettingsDialogMethods = {
  show: () => void;
  hide: () => void;
};

function SettingsDialog(props, ref) {
  const [show, setShow] = React.useState(false);

  const [theme, setTheme] = React.useState<'light-theme' | 'dark-theme'>();
  const logout = React.useCallback(() => {}, []);

  React.useImperativeHandle(ref, () => ({
    show: () => setShow(true),
    hide: () => setShow(false),
  }));

  return show ? (
    <SettingsDialogRenderer theme={theme} onThemeChange={setTheme} onLogout={logout} onHide={() => setShow(false)} />
  ) : null;
}

export default React.forwardRef<SettingsDialogMethods>(SettingsDialog);

export function SettingsDialogRenderer(props: SettingsDialogProps) {
  const { theme, onThemeChange, onLogout, onHide } = props;

  const [tab, setTab] = React.useState<'styles' | 'account'>('styles');

  return (
    <div className="settings-dialog" onClick={onHide} data-testid="dialogBackdrop">
      <div className="dialog" onClick={(event) => event.stopPropagation()}>
        <div className="heading-container">
          <div className="heading">settings</div>
          <div className="sub-heading">choose your preferences</div>
        </div>
        <div className="body">
          <div className="tab-heading">
            <div className={classnames('tab', { selected: tab === 'styles' })} onClick={() => setTab('styles')}>
              styles
            </div>
            <div className={classnames('tab', { selected: tab === 'account' })} onClick={() => setTab('account')}>
              account
            </div>
          </div>

          {tab === 'styles' && (
            <div className="tab-body styles-tab-body">
              <div className="label">appearance</div>
              <div className="tab-heading theme-tab-heading">
                <div className="theme-icon-container">
                  <img
                    src={lightThemeImage}
                    className={classnames({ selected: theme === 'light-theme' })}
                    onClick={() => onThemeChange('light-theme')}
                    alt="Light Theme"
                  />
                  <div className="theme-icon-label">light</div>
                </div>

                <div className="theme-icon-container">
                  <img
                    src={darkThemeImage}
                    className={classnames({ selected: theme === 'dark-theme' })}
                    onClick={() => onThemeChange('dark-theme')}
                    alt="Dark Theme"
                  />
                  <div className="theme-icon-label">dark</div>
                </div>
              </div>
            </div>
          )}
          {tab === 'account' && (
            <div className="tab-body account-tab-body">
              <PrimaryButton onClick={onLogout}>logout</PrimaryButton>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ui/src/app/modules/components/settings-dialog/settings-dialog.component.ts
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Router } from '@angular/router';

import versionJson from '../../../../application-version.json';
import { AuthService } from '../../auth/auth.service';
import { Themes, themeToString } from '../../domain/Theme';

enum SettingsTab {
  STYLES,
  ACCOUNT,
  INFO
}

@Component({
  selector: 'rq-settings-dialog',
  templateUrl: './settings-dialog.component.html',
  styleUrls: ['./settings-dialog.component.scss'],
  host: {
    '(click)': 'hide()',
    '[style.display]': 'visible ? "flex": "none"',
  },
})

export class SettingsDialogComponent {
  @Input() visible = false;
  @Input() teamId: string;
  @Input() theme: Themes;
  @Output() themeChanged: EventEmitter<Themes> = new EventEmitter();

  _visibleTab: SettingsTab = SettingsTab.STYLES;
  settingsTab = SettingsTab;

  constructor(private router: Router) {}

  set currentlyVisibleTab(tab: SettingsTab) {
    this._visibleTab = tab;
  }

  tabIsVisible(tab: SettingsTab): boolean {
    return this._visibleTab === tab;
  }

  show() {
    this.visible = true;
  }

  hide() {
    this.visible = false;
  }

  logoutOfAccount() {
    AuthService.clearToken();
    this.router.navigate(['login', this.teamId]);
  }

  enableDarkTheme() {
    this.enableTheme(Themes.Dark);
  }

  enableLightTheme() {
    this.enableTheme(Themes.Light);
  }

  private enableTheme(theme: Themes) {
    this.theme = theme;
    this.themeChanged.emit(this.theme);
    this.saveTheme();
  }

  get darkThemeIsEnabled(): boolean {
    return this.theme === Themes.Dark;
  }

  get lightThemeIsEnabled(): boolean {
    return this.theme === Themes.Light;
  }

  get applicationVersion(): string {
    return versionJson.version;
  }

  private saveTheme(): void {
    const themeString = themeToString(this.theme);
    if (themeString !== '') {
      localStorage.setItem('theme', themeString);
    }
    this.themeChanged.emit(this.theme);
  }
}

<!--
  ~ Copyright (c) 2021 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div
    class="dialog"
    (click)="$event.stopPropagation()"
    [ngClass]="{
        'dark-theme': darkThemeIsEnabled
    }"
>
    <div class="heading-container">
        <div class="heading">settings</div>
        <div
            class="sub-heading"
            [ngClass]="{
                'dark-theme': darkThemeIsEnabled
            }"
        >
            choose your preferences <em>(Beta)</em>
        </div>
    </div>

    <div class="body">
        <div class="tab-heading">
            <button
                class="tab"
                (click)="currentlyVisibleTab = settingsTab.STYLES"
                [ngClass]="{
                    selected: tabIsVisible(settingsTab.STYLES),
                    'dark-theme': darkThemeIsEnabled
                }"
            >
                styles
            </button>
            <button
                class="tab"
                (click)="currentlyVisibleTab = settingsTab.ACCOUNT"
                [ngClass]="{
                    selected: tabIsVisible(settingsTab.ACCOUNT),
                    'dark-theme': darkThemeIsEnabled
                }"
            >
                account
            </button>
            <button
              class="tab"
              (click)="currentlyVisibleTab = settingsTab.INFO"
              [ngClass]="{
                    selected: tabIsVisible(settingsTab.INFO),
                    'dark-theme': darkThemeIsEnabled
                }"
            >
                info
            </button>
        </div>

        <div class="tab-body styles-tab-body" *ngIf="tabIsVisible(settingsTab.STYLES)">
            <div class="label">appearance</div>
            <div class="tab-heading theme-tab-heading">
                <div class="theme-icon-container">
                    <img
                        src="./assets/light-theme-picture.jpg"
                        [ngClass]="{
                            selected: lightThemeIsEnabled
                        }"
                        (click)="enableLightTheme()"
                        alt="Light Theme"
                    />
                    <div class="theme-icon-label">light</div>
                </div>

                <div class="theme-icon-container">
                    <img
                        src="./assets/dark-theme-picture.jpg"
                        [ngClass]="{
                            selected: darkThemeIsEnabled
                        }"
                        (click)="enableDarkTheme()"
                        alt="Dark Theme"
                    />
                    <div class="theme-icon-label">dark</div>
                </div>
            </div>
        </div>

        <div class="tab-body account-tab-body" *ngIf="tabIsVisible(settingsTab.ACCOUNT)">
            <rq-button
                text="logout"
                type="primary"
                (click)="logoutOfAccount()"
            ></rq-button>
        </div>

        <div class="tab-body info-tab-body" *ngIf="tabIsVisible(settingsTab.INFO)">
            <label class="version-label">
                Version:
                <input class="version-container" id="application-version" disabled [value]="applicationVersion"/>
            </label>
        </div>
    </div>
</div>
