// ui/src/App/Team/Retro/ThoughtsColumn/ThoughtsColumn.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState } from 'react';
import { Droppable } from 'react-beautiful-dnd';
import { useRecoilValue } from 'recoil';

import ColumnHeader from '../../../../Common/ColumnHeader/ColumnHeader';
import CountSeparator from '../../../../Common/CountSeparator/CountSeparator';
import CreateColumnItemInput from '../../../../Common/CreateColumnItemInput/CreateColumnItemInput';
import ColumnService from '../../../../Services/Api/ColumnService';
import ThoughtService from '../../../../Services/Api/ThoughtService';
import { TeamState } from '../../../../State/TeamState';
import {
	ActiveThoughtCountByColumnIdState,
	SortableThoughtsByTopicState,
} from '../../../../State/ThoughtsState';
import { Column } from '../../../../Types/Column';
import { getCreateThoughtRequest } from '../../../../Types/CreateThoughtRequest';
import Thought from '../../../../Types/Thought';

import DraggableRetroItem from './DraggableThoughtItem/DraggableRetroItem';

import './ThoughtsColumn.scss';

interface Props {
	column: Column;
}

function ThoughtsColumn(props: Props) {
	const { column } = props;

	const team = useRecoilValue(TeamState);
	const [sorted, setSorted] = useState(false);
	const thoughts = useRecoilValue<Thought[]>(
		SortableThoughtsByTopicState({ columnId: column.id, sorted })
	);
	const activeThoughtCount = useRecoilValue<number>(
		ActiveThoughtCountByColumnIdState(column.id)
	);

	const changeTitle = (title: string) => {
		ColumnService.updateTitle(team.id, column.id, title).catch(console.error);
	};

	const createThought = (text: string) => {
		if (text && text.length) {
			ThoughtService.create(
				team.id,
				getCreateThoughtRequest(column.id, text)
			).catch(console.error);
		}
	};

	return (
		<div
			className="thoughts-column"
			data-testid={`retroColumn__${column.topic}`}
		>
			<ColumnHeader
				initialTitle={column.title}
				type={column.topic}
				onSort={setSorted}
				onTitleChange={changeTitle}
			/>
			<CreateColumnItemInput
				type={column.topic}
				placeholder="Enter a Thought"
				handleSubmission={createThought}
			/>
			<CountSeparator count={activeThoughtCount} />
			<Droppable droppableId={`${column.id}`} type="THOUGHT">
				{(provided) => (
					<ul
						className="thought-list"
						data-testid={`droppableThoughtColumn-${column.topic}`}
						ref={provided.innerRef}
						{...provided.droppableProps}
					>
						{thoughts.map((thought: Thought, index: number) => (
							<li key={index}>
								<DraggableRetroItem
									thought={thought}
									topic={column.topic}
									index={index}
								/>
							</li>
						))}
						{provided.placeholder}
					</ul>
				)}
			</Droppable>
		</div>
	);
}

export default ThoughtsColumn;

// ui/src/app/modules/teams/components/thoughts-column/thoughts-column.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, ElementRef, Input, ViewChild} from '@angular/core';
import {emptyThought, Thought} from '../../../domain/thought';
import {Column} from '../../../domain/column';
import {ThoughtService} from '../../services/thought.service';
import {TaskDialogComponent} from '../../../controls/task-dialog/task-dialog.component';
import {animate, sequence, style, transition, trigger} from '@angular/animations';
import {fadeInOutAnimation} from '../../../animations/add-delete-animation';

@Component({
  selector: 'rq-thoughts-column',
  templateUrl: './thoughts-column.component.html',
  styleUrls: ['./thoughts-column.component.scss'],
  animations: [fadeInOutAnimation]
})
export class ThoughtsColumnComponent {
  constructor(private thoughtService: ThoughtService) {
  }

  @Input() column: Column;
  @Input() thoughts: Array<Thought> = [];

  @ViewChild('thoughtDialog') thoughtDialog: TaskDialogComponent;

  selectedThought: Thought = emptyThought();
  dialogIsVisible = false;

  discussThought(thought: Thought): void {
    thought.discussed = !thought.discussed;
    this.thoughtService.updateThought(thought);
  }

  heartThought(thought: Thought): void {
    thought.hearts++;
    this.thoughtService.updateThought(thought);
  }

  onMessageChanged(message: string, thought: Thought) {
    thought.message = message;
    this.thoughtService.updateThought(thought);
  }

  onDeleted(thought: Thought) {
    this.thoughtService.deleteThought(thought);
  }

  starCountChanged(starCount: number, thought: Thought) {
    thought.hearts = starCount;
    this.thoughtService.updateThought(thought);
  }

  onCompleted(completedState: boolean, thought: Thought) {
    thought.discussed = completedState;
    this.thoughtService.updateThought(thought);
  }

  displayPopup(thought: Thought) {
    this.selectedThought = thought;
    this.thoughtDialog.show();
  }

}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="rq-thought-list {{column.topic}}">
  <rq-task
    *ngFor="let thought of allThoughts"
    [task]="thought"
    [type]="column.topic"
    (messageChanged)="onMessageChanged($event, thought)"
    (deleted)="onDeleted($event)"
    (messageClicked)="displayPopup(thought)"
    (starCountIncreased)="starCountChanged($event, thought)"
    (completed)="onCompleted($event, thought)"
    [@fadeInOutAnimation]="thought.state"
    [readOnly]="readOnly"
    [theme]="theme"
    [archived]="archived"
  >
  </rq-task>
</div>

<rq-task-dialog
  #thoughtDialog
  [teamId]="teamId"
  [theme]="theme"
  [visible]="dialogIsVisible"
  [type]="column.topic"
  [task]="selectedThought"
  (visibilityChanged)="dialogIsVisible = $event"
  (messageChanged)="onMessageChanged($event, selectedThought)"
  (deleted)="onDeleted($event)"
  (starCountIncreased)="starCountChanged($event, selectedThought)"
  (completed)="onCompleted($event, selectedThought)"
></rq-task-dialog>
