// ui/src/Common/FloatingCharacterCountdown/FloatingCharacterCountdown.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { ReactElement } from 'react';
import classNames from 'classnames';

import './FloatingCharacterCountdown.scss';

interface Props {
	characterCount: number;
	maxCharacterCount?: number;
	charsAreRunningOutThreshold?: number;
}

export default function FloatingCharacterCountdown(props: Props): ReactElement {
	const {
		maxCharacterCount = 255,
		charsAreRunningOutThreshold = 20,
		characterCount = 0,
	} = props;

	const charactersRemaining = maxCharacterCount - characterCount;
	const charactersRemainingHaveRunOut = charactersRemaining <= 0;
	const charactersRemainingAreBelowThreshold =
		charactersRemaining < charsAreRunningOutThreshold;
	const charactersRemainingAreAboutToRunOut =
		charactersRemainingAreBelowThreshold && !charactersRemainingHaveRunOut;

	const className = classNames('floating-character-countdown', {
		visible: characterCount,
		'display-warning-text': charactersRemainingAreAboutToRunOut,
		'display-error-text': charactersRemainingHaveRunOut,
	});

	return <span className={className}>{charactersRemaining}</span>;
}

// ui/src/app/modules/controls/floating-character-countdown/floating-character-countdown.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, Input} from '@angular/core';

@Component({
  selector: 'rq-floating-character-countdown',
  templateUrl: './floating-character-countdown.component.html',
  styleUrls: ['./floating-character-countdown.component.scss'],
  host: {
    '[class.display-warning-text]': 'charactersRemainingAreAboutToRunOut()',
    '[style.visibility]': 'textIsEmpty() ? \'hidden\' : \'visible\''
  }
})
export class FloatingCharacterCountdownComponent {

  @Input() maxCharacterCount = 255;
  @Input() charsAreRunningOutThreshold = 50;
  @Input() characterCount = 0;

  constructor() { }

  public charactersRemaining(): number {
    return this.maxCharacterCount - this.characterCount;
  }

  public charactersRemainingAreAboutToRunOut(): boolean {
    return this.charactersRemaining() < this.charsAreRunningOutThreshold;
  }

  public textIsEmpty(): boolean {
    return this.characterCount === 0;
  }

}

<!--
  ~  Copyright (c) 2018 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->
{{charactersRemaining()}}
