// ui/src/app/modules/controls/feedback-dialog/feedback-dialog.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output} from '@angular/core';
import {emptyFeedback, Feedback} from '../../domain/feedback';

@Component({
  selector: 'rq-feedback-dialog',
  templateUrl: './feedback-dialog.component.html',
  styleUrls: ['./feedback-dialog.component.scss'],
  host: {
    '(click)': 'hide()',
    '[style.display]': 'visible ? "flex": "none"'
  }
})
export class FeedbackDialogComponent {

  @Input() visible = false;

  @Output() visibilityChanged: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Output() submitted: EventEmitter<Feedback> = new EventEmitter<Feedback>();

  feedback: Feedback = emptyFeedback();
  starStates: Array<boolean> = [false, false, false, false, false];
  starsClicked = false;

  public hide(): void {
    this.visible = false;
    this.visibilityChanged.emit(this.visible);
    this.feedback = emptyFeedback();
    this.starsClicked = false;
    this.clearStars();
  }

  public show(): void {
    this.visible = true;
  }

  public onSendButtonClicked(): void {
    this.submitted.emit(this.feedback);
    this.hide();
  }

  public onStarHovered(index: number): void {

    const starRating = index + 1;

    if (!this.starsClicked) {

      this.clearStars();

      for (let i = 0; i < starRating; ++i) {
        this.starStates[i] = true;
      }
      this.feedback.stars = starRating;
    }
  }

  public clearStars(): void {
    if (!this.starsClicked) {
      for (let i = 0; i < this.starStates.length; ++i) {
        this.starStates[i] = false;
      }
      this.feedback.stars = 0;
    }
  }

  public onStarClicked(index: number): void {
    if (this.starsClicked) {
      this.starsClicked = false;
      this.onStarHovered(index);
    }
    this.starsClicked = true;
  }
}


<!--
  ~  Copyright (c) 2020 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<div
  class="dialog"
  [ngClass]="{
    'dark-theme': darkThemeIsEnabled
  }"
  (click)="$event.stopPropagation()"
>

  <div class="body">
    <div
      class="heading"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    >feedback
    </div>
    <div
      class="sub-heading"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    >How can we improve RetroQuest?
    </div>

    <div
      class="section star-line"
      (mouseleave)="clearStars()"
    >
      <div
        class="fa-star"
        *ngFor="let starState of starStates; let i = index"
        [ngClass]="{
          'active': starState,
          'fas': starState,
          'far': !starState
        }"
        (mouseenter)="onStarHovered(i)"
        (click)="onStarClicked(i)"
      ></div>
    </div>

    <div class="section comments-section">
      <div
        class="label"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      >comments<span class="required-field">*</span></div>
      <textarea
        [(ngModel)]="feedback.comment"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      ></textarea>
    </div>

    <div class="section feedback-email-section">
      <div
        class="label"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      >feedback email
      </div>
      <input
        [type]="'text'"
        [(ngModel)]="feedback.userEmail"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      />
    </div>

  </div>
  <div class="footer">

    <div class="container">
      <rq-button
        type="secondary"
        text="cancel"
        (click)="hide()"
        [theme]="theme"
      ></rq-button>
    </div>
    <div class="container">
      <rq-button
        type="primary"
        text="send!"
        (click)="onSendButtonClicked()"
      ></rq-button>
    </div>

  </div>
</div>

// ui/src/react/components/feedback-dialog/FeedbackDialog.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';

import Dialog from '../dialog/Dialog';
import Modal, { ModalMethods } from '../modal/Modal';
import FeedbackStars from '../feedback-stars/FeedbackStars';
import useBoard from '../../hooks/useBoard';
import Feedback from '../../types/Feedback';

import './FeedbackDialog.scss';

function FeedbackDialog(props, ref) {
  const { teamId } = useBoard();

  function hide() {
    ref.current?.hide();
  }

  return (
    <Modal ref={ref}>
      <FeedbackDialogRenderer teamId={teamId} onSubmit={hide} onCancel={hide} />
    </Modal>
  );
}

type FeedbackDialogRendererProps = {
  teamId: string;
  onSubmit: (feedback: Feedback) => void;
  onCancel: () => void;
};

export function FeedbackDialogRenderer(props: FeedbackDialogRendererProps) {
  const { teamId, onSubmit, onCancel } = props;

  const [stars, setStars] = React.useState(0);
  const [comment, setComment] = React.useState<string>('');
  const [userEmail, setUserEmail] = React.useState<string>('');

  function handleSubmit() {
    if (comment) {
      onSubmit({
        teamId,
        stars,
        comment,
        userEmail,
      });
    }
  }

  return (
    <Dialog
      className="feedback-dialog"
      header="feedback"
      subHeader="How can we improve RetroQuest?"
      buttons={{
        cancel: { text: 'cancel', onClick: onCancel },
        confirm: { text: 'send!', onClick: handleSubmit },
      }}
    >
      <FeedbackStars className="section" value={stars} onChange={setStars} />

      <div className="section comments-section">
        <label className="label" htmlFor="comments">
          comments<span className="required-field">*</span>
        </label>
        <textarea id="comments" value={comment} onChange={(e) => setComment(e.target.value)} />
      </div>

      <div className="section feedback-email-section">
        <label className="label" htmlFor="email">
          feedback email
        </label>
        <input id="email" type="text" value={userEmail} onChange={(e) => setUserEmail(e.target.value)} />
      </div>
    </Dialog>
  );
}

export default React.forwardRef<ModalMethods>(FeedbackDialog);
