// ui/src/react/components/deletion-overlay/DeletionOverlay.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';

import { PrimaryButton, SecondaryButton } from '../button/Button';
import './DeletionOverlay.scss';

interface OverlayProps {
  header?: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export default function DeletionOverlay(props: OverlayProps): React.ReactElement {
  const { header = '', onConfirm, onCancel } = props;

  return (
    <div className="deletion-overlay">
      <input autoFocus={true} className="hidden-input" onBlur={onCancel} />
      <div className="heading">
        <p>{header}</p>
      </div>
      <div className="button-container">
        <SecondaryButton className="delete-decline-button" onMouseDown={(e) => e.preventDefault()} onClick={onCancel}>
          No
        </SecondaryButton>
        <PrimaryButton className="delete-accept-button" onMouseDown={(e) => e.preventDefault()} onClick={onConfirm}>
          Yes
        </PrimaryButton>
      </div>
    </div>
  );
}

// ui/src/app/modules/controls/deletion-overlay/deletion-overlay.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, EventEmitter } from '@angular/core';
import {ViewChild} from '@angular/core';
import {ElementRef} from '@angular/core';
import {Output, Input} from '@angular/core';
import {OnInit} from '@angular/core';

@Component({
  selector: 'rq-deletion-overlay',
  templateUrl: './deletion-overlay.component.html',
  styleUrls: ['./deletion-overlay.component.scss']
})
export class DeletionOverlayComponent implements OnInit {

  @Input() heading = '';

  @Output() acceptButtonClicked: EventEmitter<void> = new EventEmitter<void>();
  @Output() declineButtonClicked: EventEmitter<void> = new EventEmitter<void>();
  @Output() blur: EventEmitter<void> = new EventEmitter<void>();

  @ViewChild('hiddenDeleteInput') hiddenDeleteInput: ElementRef;

  public ngOnInit(): void {
    setTimeout(() => {
      this.hiddenDeleteInput.nativeElement.focus();
    }, 0);
  }

  emitAcceptButtonClicked() {
    this.acceptButtonClicked.emit();
  }

  emitDeclineButtonClicked() {
    this.declineButtonClicked.emit();
  }

  emitBlur() {
    this.blur.emit();
  }

}

<!--
  ~  Copyright (c) 2018 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<input
  #hiddenDeleteInput
  class="hidden-input"
  (blur)="emitBlur()"
>

<div class="heading">
  <div>{{heading}}</div>
</div>

<div
  class="button-container"
  [ngClass]="{
    'dark-theme': darkThemeIsEnabled
  }"
>
  <rq-button
    class="delete-decline-button"
    [ngClass]="{
      'dark-mode': darkThemeIsEnabled
    }"
    type="secondary"
    text="no"
    (click)="emitDeclineButtonClicked()"
  ></rq-button>
  <rq-button
    class="delete-accept-button"
    type="primary"
    text="yes"
    (mousedown)="$event.preventDefault()"
    (click)="emitAcceptButtonClicked(); hiddenDeleteInput.blur()"
  ></rq-button>
</div>
