// ui/src/App/Team/Retro/RetroSubheader/FeedbackDialog/FeedbackDialog.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState } from 'react';
import { useRecoilValue, useSetRecoilState } from 'recoil';

import Dialog from '../../../../../Common/Dialog/Dialog';
import FeedbackService from '../../../../../Services/Api/FeedbackService';
import { ModalContentsState } from '../../../../../State/ModalContentsState';
import { TeamState } from '../../../../../State/TeamState';

import FeedbackStars from './FeedbackStars/FeedbackStars';

import './FeedbackDialog.scss';

function FeedbackDialog() {
	const setModalContents = useSetRecoilState(ModalContentsState);
	const team = useRecoilValue(TeamState);
	const [stars, setStars] = useState(0);
	const [comment, setComment] = useState<string>('');
	const [userEmail, setUserEmail] = useState<string>('');

	const closeModal = () => setModalContents(null);

	const handleSubmit = () => {
		if (comment) {
			const feedback = {
				teamId: team.id,
				stars,
				comment,
				userEmail,
			};
			FeedbackService.addFeedback(feedback)
				.then(() => closeModal())
				.catch(console.error);
		}
	};

	return (
		<Dialog
			testId="feedbackDialog"
			className="feedback-dialog"
			title="Feedback"
			subtitle="How can we improve RetroQuest?"
			buttons={{
				cancel: { text: 'Cancel', onClick: closeModal },
				confirm: { text: 'Send!', onClick: handleSubmit },
			}}
		>
			<FeedbackStars className="section" value={stars} onChange={setStars} />
			<div className="section comments-section">
				<label className="label" htmlFor="comments">
					Comments<span className="required-field">*</span>
				</label>
				<textarea
					className="comments-textarea"
					id="comments"
					value={comment}
					onChange={(event) => setComment(event.target.value)}
				/>
			</div>
			<div className="section feedback-email-section">
				<label className="label" htmlFor="email">
					Feedback Email
				</label>
				<input
					className="email-input"
					id="email"
					type="text"
					value={userEmail}
					onChange={(event) => setUserEmail(event.target.value)}
				/>
			</div>
		</Dialog>
	);
}

export default FeedbackDialog;

// ui/src/app/modules/controls/feedback-dialog/feedback-dialog.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output} from '@angular/core';
import {emptyFeedback, Feedback} from '../../domain/feedback';

@Component({
  selector: 'rq-feedback-dialog',
  templateUrl: './feedback-dialog.component.html',
  styleUrls: ['./feedback-dialog.component.scss'],
  host: {
    '(click)': 'hide()',
    '[style.display]': 'visible ? "flex": "none"'
  }
})
export class FeedbackDialogComponent {

  @Input() visible = false;

  @Output() visibilityChanged: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Output() submitted: EventEmitter<Feedback> = new EventEmitter<Feedback>();

  feedback: Feedback = emptyFeedback();
  starStates: Array<boolean> = [false, false, false, false, false];
  starsClicked = false;

  public hide(): void {
    this.visible = false;
    this.visibilityChanged.emit(this.visible);
    this.feedback = emptyFeedback();
    this.starsClicked = false;
    this.clearStars();
  }

  public show(): void {
    this.visible = true;
  }

  public onSendButtonClicked(): void {
    this.submitted.emit(this.feedback);
    this.hide();
  }

  public onStarHovered(index: number): void {

    const starRating = index + 1;

    if (!this.starsClicked) {

      this.clearStars();

      for (let i = 0; i < starRating; ++i) {
        this.starStates[i] = true;
      }
      this.feedback.stars = starRating;
    }
  }

  public clearStars(): void {
    if (!this.starsClicked) {
      for (let i = 0; i < this.starStates.length; ++i) {
        this.starStates[i] = false;
      }
      this.feedback.stars = 0;
    }
  }

  public onStarClicked(index: number): void {
    if (this.starsClicked) {
      this.starsClicked = false;
      this.onStarHovered(index);
    }
    this.starsClicked = true;
  }
}


<!--
  ~  Copyright (c) 2020 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<div
  class="dialog"
  [ngClass]="{
    'dark-theme': darkThemeIsEnabled
  }"
  (click)="$event.stopPropagation()"
>

  <div class="body">
    <div
      class="heading"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    >feedback
    </div>
    <div
      class="sub-heading"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    >How can we improve RetroQuest?
    </div>

    <div
      class="section star-line"
      (mouseleave)="clearStars()"
    >
      <div
        class="fa-star"
        *ngFor="let starState of starStates; let i = index"
        [ngClass]="{
          'active': starState,
          'fas': starState,
          'far': !starState
        }"
        (mouseenter)="onStarHovered(i)"
        (click)="onStarClicked(i)"
      ></div>
    </div>

    <div class="section comments-section">
      <div
        class="label"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      >comments<span class="required-field">*</span></div>
      <textarea
        [(ngModel)]="feedback.comment"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      ></textarea>
    </div>

    <div class="section feedback-email-section">
      <div
        class="label"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      >feedback email
      </div>
      <input
        [type]="'text'"
        [(ngModel)]="feedback.userEmail"
        [ngClass]="{
          'dark-theme': darkThemeIsEnabled
        }"
      />
    </div>

  </div>
  <div class="footer">

    <div class="container">
      <rq-button
        type="secondary"
        text="cancel"
        (click)="hide()"
        [theme]="theme"
      ></rq-button>
    </div>
    <div class="container">
      <rq-button
        type="primary"
        text="send!"
        (click)="onSendButtonClicked()"
      ></rq-button>
    </div>

  </div>
</div>
