// ui/src/app/modules/teams/components/modal/modal.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output} from '@angular/core';

@Component({
  selector: 'rq-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.scss']
})
export class ModalComponent {
  @Input() isOpen = false;
  @Output() close = new EventEmitter();

  closeModal() {
    this.isOpen = false;
    this.close.emit();
  }
}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="modal-wrapper" [hidden]="!isOpen">
  <div class="modal">
    <ng-content select=".modal-header"></ng-content>
    <ng-content select=".modal-body"></ng-content>
    <ng-content select=".modal-footer"></ng-content>
  </div>

  <div class="modal-background" (click)="closeModal()"></div>
</div>

// ui/src/Common/Modal/Modal.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useCallback, useEffect } from 'react';
import { useA11yDialog } from 'react-a11y-dialog';
import { useRecoilState } from 'recoil';

import {
	ModalContents,
	ModalContentsState,
} from '../../State/ModalContentsState';

import './Modal.scss';

function Modal() {
	const [modalContents, setModalContents] =
		useRecoilState<ModalContents | null>(ModalContentsState);

	const [modalInstance, attr] = useA11yDialog({
		id: 'modal-container',
		title: modalContents?.title,
	});

	const dataTestId = `${modalContents?.title
		.toLowerCase()
		.replace(' ', '-')}-modal`;

	const clearModalContents = useCallback(
		() => setModalContents(null),
		[setModalContents]
	);

	useEffect(() => {
		if (modalContents) {
			modalInstance?.show();
		} else {
			modalInstance?.hide();
			clearModalContents();
		}
	}, [clearModalContents, modalContents, modalInstance]);

	return (
		<div
			{...attr.container}
			className="modal-container"
			data-testid={dataTestId}
		>
			<div
				{...attr.overlay}
				className="modal-overlay"
				data-testid="modalOverlay"
				onClick={clearModalContents}
			/>
			<div
				{...attr.dialog}
				className={`modal-content ${
					modalContents?.superSize ? 'super-size' : ''
				}`}
			>
				<p {...attr.title} className="modal-title">
					{modalContents?.title}
				</p>
				{modalContents?.component}
				<button
					{...attr.closeButton}
					className="modal-close-button"
					aria-label="Close Modal"
					onClick={clearModalContents}
				>
					<i className="fas fa-close close-icon" aria-hidden />
				</button>
			</div>
		</div>
	);
}

export default Modal;
