// ui/src/app/modules/components/contributors/contributors.component.ts
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit } from '@angular/core';

import { Contributor } from '../../domain/contributor';

import { ContributorsService } from './contributors.service';

@Component({
  selector: 'rq-contributors',
  templateUrl: './contributors.component.html',
  styleUrls: ['./contributors.component.scss'],
})
export class ContributorsComponent implements OnInit {
  contributors: Contributor[][];

  ROW_SIZE = 5;

  constructor(private contributorService: ContributorsService) {}

  ngOnInit() {
    this.contributorService.getContributors().subscribe((result) => {
      const rows = Math.ceil(result.length / 5);
      this.contributors = new Array(rows);
      let currentRow;
      let contributorsPos = 0;
      for (currentRow = 0; currentRow < this.contributors.length; currentRow++) {
        this.contributors[currentRow] = new Array(this.remaningSpace(result, currentRow));
        let currentColumn;
        for (currentColumn = 0; currentColumn < this.contributors[currentRow].length; currentColumn++) {
          this.contributors[currentRow][currentColumn] = result[contributorsPos];
          contributorsPos++;
        }
      }
    });
  }

  private rowCountFromContributorCount(contributors: Contributor[]) {
    return Math.ceil(contributors.length / this.ROW_SIZE);
  }

  private remaningSpace(contributors: Contributor[], currentRow: number): number {
    const rows = this.rowCountFromContributorCount(contributors);
    const leftover: number = contributors.length % this.ROW_SIZE;
    if (currentRow === rows - 1) {
      return leftover;
    }
    return this.ROW_SIZE;
  }
}

<!--
  ~  Copyright (c) 2020 Ford Motor Company
  ~  All rights reserved.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~  http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  -->

<div class="contributors">
    <div class="contributors-title-container">
        <div class="contributors-title">Code Contributors</div>
        <div class="contributors-sub-title">
            Some of the people that help make
            <span class="logo-span">RetroQuest</span> possible
        </div>
    </div>

    <div *ngFor="let contributorRow of contributors">
        <a
            *ngFor="let contributor of contributorRow"
            href="{{ contributor.accountUrl }}"
            target="_blank"
            rel="noopener"
        >
            <img [src]="contributor.image" alt="{{ contributor.accountUrl }}" />
        </a>
    </div>
</div>

// ui/src/Common/AuthTemplate/Contributors/Contributors.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import { useEffect, useState } from 'react';

import ContributorsService from '../../../Services/Api/ContributorsService';
import { Contributor } from '../../../Types/Contributor';

import './Contributors.scss';

export default function Contributors() {
	const [contributors, setContributors] = useState<Contributor[]>([]);

	useEffect(() => {
		ContributorsService.getContributors().then((contributorArray) => {
			setContributors(
				contributorArray.map((contributor) => ({
					accountUrl: contributor.accountUrl,
					image: `data:image/png;base64,${contributor.image}`,
				}))
			);
		});
	}, []);

	return (
		<div className="contributors">
			<div className="contributors-title-container">
				<div className="contributors-title">Code Contributors</div>
				<div className="contributors-sub-title">
					Some of the people that help make{' '}
					<span className="logo-span">RetroQuest</span> possible
				</div>
			</div>
			<div className="contributor-list">
				{contributors.map((contributor, index) => (
					<a
						href={contributor.accountUrl}
						target="_blank"
						rel="noopener noreferrer"
						key={contributor.accountUrl}
						data-testid={`rq-contributor-${index}`}
					>
						<img src={contributor.image} alt={contributor.accountUrl} />
					</a>
				))}
			</div>
		</div>
	);
}
