// ui/src/app/modules/components/top-header/top-header.component.ts
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, EventEmitter, Input, OnInit, Output, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

import { Themes } from '../../domain/Theme';
import { SaveCheckerService } from '../../teams/services/save-checker.service';
import { SettingsDialogComponent } from '../settings-dialog/settings-dialog.component';

@Component({
  selector: 'rq-top-header',
  templateUrl: './top-header.component.html',
  styleUrls: ['./top-header.component.scss'],
})
export class TopHeaderComponent implements OnInit {
  @Input() teamName: string;
  @Input() teamId: string;

  @Input() theme: Themes;

  @Output() themeChanged: EventEmitter<Themes> = new EventEmitter();

  @ViewChild(SettingsDialogComponent) settingsDialog: SettingsDialogComponent;

  @Input() selectedView = '';

  constructor(private router: Router, private saveCheckerService: SaveCheckerService) {}

  ngOnInit(): void {
    if (this.router.url.endsWith(this.teamId)) {
      this.changeView('retro');
    } else if (this.router.url.includes('archives')) {
      this.changeView('archives');
    } else if (this.router.url.endsWith('radiator')) {
      this.changeView('radiator');
    }
  }

  get retroViewIsSelected(): boolean {
    return this.selectedView === 'retro';
  }

  get radiatorViewIsSelected(): boolean {
    return this.selectedView === 'radiator';
  }

  get archivesViewIsSelected(): boolean {
    return this.selectedView === 'archives';
  }

  get darkThemeIsEnabled(): boolean {
    return this.theme === Themes.Dark;
  }

  get lastSavedText(): string {
    if (this.saveCheckerService.lastSavedDateTime === '') {
      return 'All changes saved';
    }

    return 'Last change saved at ' + this.saveCheckerService.lastSavedDateTime;
  }

  isSelected(view: string): boolean {
    return this.selectedView === view;
  }

  changeView(view: string) {
    this.selectedView = view;

    switch (view) {
      case 'retro': {
        this.router.navigateByUrl(`/team/${this.teamId}`);
        break;
      }
      case 'archives': {
        this.router.navigateByUrl(`/team/${this.teamId}/archives`);
        break;
      }
      case 'radiator': {
        this.router.navigateByUrl(`/team/${this.teamId}/radiator`);
        break;
      }
      default:
        break;
    }
  }
}

<!--
  ~ Copyright (c) 2021 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="header-top-content">
    <div class="left-content">
        <a routerLink="/" class="logo-link">
            <img
                [src]="
                    darkThemeIsEnabled
                        ? '/assets/icons/icon-light-72x72.png'
                        : '/assets/icons/icon-72x72.png'
                "
                title="RetroQuest"
                id="logo"
                [ngClass]="{
                    'dark-theme': darkThemeIsEnabled
                }"
                alt="RetroQuest"
            />
        </a>
        <div
            class="horizontal-separator"
            [ngClass]="{
                'dark-theme': darkThemeIsEnabled
            }"
        ></div>
        <div
            id="teamName"
            [ngClass]="{
                'dark-theme': darkThemeIsEnabled
            }"
        >
            {{ teamName }}
        </div>
    </div>

    <div class="center-content">
        <rq-button
            class="retro-view-button"
            [type]="retroViewIsSelected ? 'primary' : 'secondary'"
            text="retro"
            [theme]="theme"
            [ngClass]="{ selected: retroViewIsSelected }"
            (click)="changeView('retro')"
        ></rq-button>

        <rq-button
            class="archives-view-button"
            [type]="archivesViewIsSelected ? 'primary' : 'secondary'"
            text="archives"
            [theme]="theme"
            [ngClass]="{ selected: archivesViewIsSelected }"
            (click)="changeView('archives')"
        ></rq-button>

        <rq-button
            class="radiator-view-button"
            [type]="radiatorViewIsSelected ? 'primary' : 'secondary'"
            text="radiator"
            [theme]="theme"
            [ngClass]="{ selected: radiatorViewIsSelected }"
            (click)="changeView('radiator')"
        ></rq-button>
    </div>

    <div
        class="right-content"
        [ngClass]="{
            'dark-theme': darkThemeIsEnabled
        }"
    >
        <div class="last-saved-text">{{ lastSavedText }}</div>
        <div
            class="settings-button fas fa-cog"
            (click)="settingsDialog.show()"
        ></div>
    </div>
</div>

<rq-settings-dialog
    #settingsDialog
    [teamId]="teamId"
    [theme]="theme"
    (themeChanged)="themeChanged.emit($event)"
></rq-settings-dialog>

// ui/src/react/components/top-header/TopHeader.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import { Link, NavLink } from 'react-router-dom';

import useBoard from '../../hooks/useBoard';
import useTheme from '../../hooks/useTheme';
import SaveCheckerService from '../../services/SaveCheckerService';
import SettingsDialog from '../settings-dialog/SettingsDialog';
import Dialog from '../../types/dialog';
import Theme from '../../types/theme';

import './TopHeader.scss';

import logoLight from '../../../assets/icons/icon-light-72x72.png';
import logoDark from '../../../assets/icons/icon-72x72.png';

type RqLink = {
  label: 'retro' | 'archives' | 'radiator';
  path: string;
};

const LINKS: RqLink[] = [
  { label: 'retro', path: '' },
  { label: 'archives', path: '/archives' },
  { label: 'radiator', path: '/radiator' },
];

export default function TopHeader() {
  const { teamId, teamName } = useBoard();

  const [theme] = useTheme();

  const dialogRef = React.useRef<Dialog>();

  const lastSavedText = React.useMemo(() => {
    if (SaveCheckerService.lastSavedDateTime === '') {
      return 'All changes saved';
    }
    return 'Last change saved at ' + SaveCheckerService.lastSavedDateTime;
  }, []);

  return (
    <div className="top-header">
      <div className="header-top-content">
        <div className="left-content">
          <Link to="/" className="logo-link">
            <img src={theme === Theme.DARK ? logoLight : logoDark} title="RetroQuest" id="logo" alt="RetroQuest" />
          </Link>
          <div className="horizontal-separator" />
          <div id="teamName">{teamName}</div>
        </div>

        <div className="center-content">
          {LINKS.map((link) => (
            <NavLink
              key={link.path}
              className="nav-link button"
              to={`/team/${teamId}${link.path}`}
              activeClassName="selected"
              exact={true}
            >
              {link.label}
            </NavLink>
          ))}
        </div>

        <div className="right-content">
          <div className="last-saved-text">{lastSavedText}</div>
          <div
            className="settings-button fas fa-cog"
            onClick={() => dialogRef.current?.show()}
            data-testid="settingsBtn"
          />
        </div>
      </div>
      <SettingsDialog ref={dialogRef} />
    </div>
  );
}
