// ui/src/app/modules/teams/components/top-header/top-header.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'rq-top-header',
  templateUrl: './top-header.component.html',
  styleUrls: ['./top-header.component.scss']
})
export class TopHeaderComponent {
  @Input() teamName: string;
  @Input() lastSavedText: string;

}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="header-top-content">
  <a routerLink="/" class="logo-link">
    <img
      [src]="darkThemeIsEnabled ? '/assets/icons/icon-light-72x72.png' : '/assets/icons/icon-72x72.png'"
      title="RetroQuest"
      id="logo"
      [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
    />
  </a>
  <div
    class="horizontal-separator"
    [ngClass]="{
        'dark-theme': darkThemeIsEnabled
      }"
  ></div>
  <div
    id="teamName"
    [ngClass]="{
      'dark-theme': darkThemeIsEnabled
    }"
  >{{teamName}}
  </div>

  <div class="center-content">
    <div class="view-button-container">
      <rq-button
        class="retro-view-button"
        type="secondary"
        text="retro"
        [theme]="theme"
        [ngClass]="{'selected': isSelected('retro')}"
        (click)="changeView('retro')"
      ></rq-button>

      <div class="selection-underline" *ngIf="isSelected('retro')"></div>
    </div>

    <div class="horizontal-separator" [ngClass]="{'dark-theme': darkThemeIsEnabled}"></div>

    <div class="view-button-container">

      <rq-button
        class="archives-view-button"
        type="secondary"
        text="archives"
        [theme]="theme"
        [ngClass]="{'selected': isSelected('archives')}"
        (click)="changeView('archives')"
      ></rq-button>

      <div class="selection-underline" *ngIf="isSelected('archives')"></div>
    </div>

  </div>

  <div class="right-content">
    <div class="last-saved-text">{{lastSavedText}}</div>
    <div class="settings-button fas fa-cog" (click)="settingsDialog.show()"></div>
  </div>

</div>

<rq-settings-dialog
  #settingsDialog
  [teamId]="teamId"
  [theme]="theme"
  (themeChanged)="themeChanged.emit($event)"
></rq-settings-dialog>

// ui/src/react/components/top-header/TopHeader.tsx
/*
 * Copyright (c) 2021 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import { Link, NavLink } from 'react-router-dom';

import useBoard from '../../hooks/useBoard';
import useTheme from '../../hooks/useTheme';
import SaveCheckerService from '../../services/SaveCheckerService';
import SettingsDialog from '../settings-dialog/SettingsDialog';
import Dialog from '../../types/dialog';
import Theme from '../../types/theme';

import './TopHeader.scss';

import logoLight from '../../../assets/icons/icon-light-72x72.png';
import logoDark from '../../../assets/icons/icon-72x72.png';

type RqLink = {
  label: 'retro' | 'archives' | 'radiator';
  path: string;
};

const LINKS: RqLink[] = [
  { label: 'retro', path: '' },
  { label: 'archives', path: '/archives' },
  { label: 'radiator', path: '/radiator' },
];

export default function TopHeader() {
  const { teamId, teamName } = useBoard();

  const [theme] = useTheme();

  const dialogRef = React.useRef<Dialog>();

  const lastSavedText = React.useMemo(() => {
    if (SaveCheckerService.lastSavedDateTime === '') {
      return 'All changes saved';
    }
    return 'Last change saved at ' + SaveCheckerService.lastSavedDateTime;
  }, []);

  return (
    <div className="top-header">
      <div className="header-top-content">
        <div className="left-content">
          <Link to="/" className="logo-link">
            <img src={theme === Theme.DARK ? logoLight : logoDark} title="RetroQuest" id="logo" alt="RetroQuest" />
          </Link>
          <div className="horizontal-separator" />
          <div id="teamName">{teamName}</div>
        </div>

        <div className="center-content">
          {LINKS.map((link) => (
            <NavLink
              key={link.path}
              className="nav-link button"
              to={`/team/${teamId}${link.path}`}
              activeClassName="selected"
              exact={true}
            >
              {link.label}
            </NavLink>
          ))}
        </div>

        <div className="right-content">
          <div className="last-saved-text">{lastSavedText}</div>
          <div
            className="settings-button fas fa-cog"
            onClick={() => dialogRef.current?.show()}
            data-testid="settingsBtn"
          />
        </div>
      </div>
      <SettingsDialog ref={dialogRef} />
    </div>
  );
}
