// ui/src/app/modules/teams/components/header/header.component.ts
/*
 * Copyright (c) 2018 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, Output, ViewChild} from '@angular/core';
import {EndRetroDialogComponent} from '../../../controls/end-retro-dialog/end-retro-dialog.component';
import {FeedbackService} from '../../services/feedback.service';
import {Feedback} from '../../../domain/feedback';
import {FeedbackDialogComponent} from '../../../controls/feedback-dialog/feedback-dialog.component';
import {ActionItem} from '../../../domain/action-item';

@Component({
  selector: 'rq-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {
  @Input() teamName: string;
  @Input() teamId: string;

  @Output() endRetro: EventEmitter<void> = new EventEmitter<void>();
  @Output() actionsRadiatorViewClicked: EventEmitter<void> = new EventEmitter<void>();

  @ViewChild(FeedbackDialogComponent) feedbackDialog: FeedbackDialogComponent;
  @ViewChild(EndRetroDialogComponent) endRetroDialog: EndRetroDialogComponent;

  constructor(private feedbackService: FeedbackService) {

  }

  public getCsvUrl(): string {
    return `api/team/${this.teamId}/csv`;
  }

  public showEndRetroDialog(): void {
    this.endRetroDialog.show();
  }

  public onEndRetroDialogSubmitted(): void {
    this.endRetro.emit();
  }

  public onFeedbackSubmitted(feedback: Feedback) {
    feedback.teamId = this.teamId;
    this.feedbackService.addFeedback(feedback).subscribe();
  }

  public onActionsRadiatorViewClicked(): void {
    this.actionsRadiatorViewClicked.emit();
  }
}

<!--
  ~ Copyright (c) 2018 Ford Motor Company
  ~ All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<header id="header">

  <rq-top-header [teamName]="teamName" [lastSavedText]="lastSavedText"></rq-top-header>

  <div id="headerBottom">
    <div
      class="header-bottom-content"
      [ngClass]="{
          'center-content': actionsRadiatorViewEnabled
      }"
    >

      <rq-button
        class="actions-radiator-button"
        type="secondary"
        [text]="actionsRadiatorViewEnabled ? 'view retro' : 'actions radiator'"
        (click)="onActionsRadiatorViewClicked()"
      ></rq-button>

      <button id="giveFeedback" class="rq-button-secondary" (click)="feedbackDialog.show()">
        <span class="button-text">Give Feedback</span>
        <i class="far fa-comments button-icon"></i>
      </button>

      <a routerLink="/team/{{teamId}}/archives">
        <button class="rq-button-secondary">
          <span class="button-text">Archives</span>
        </button>
      </a>

      <a id="downloadCsv"
         [href]="getCsvUrl()"
         [ngClass]="{
            'hide': actionsRadiatorViewEnabled
         }"
      >
        <button class="rq-button-secondary">
          <span class="button-text">Download CSV</span>
          <i class="fas fa-download button-icon"></i>
        </button>
      </a>

      <button
        id="endRetro"
        class="rq-button-primary"
        (click)="showEndRetroDialog()"
        [ngClass]="{
            'hide': actionsRadiatorViewEnabled
         }"
      >
        <span class="button-text">End Retro</span>
      </button>
    </div>
  </div>

</header>


<rq-feedback-dialog
  #feedbackDialog
  (submitted)="onFeedbackSubmitted($event)"
></rq-feedback-dialog>

<rq-end-retro-dialog
  #endRetroModal
  [visible]="false"
  (submitted)="onEndRetroDialogSubmitted()"
></rq-end-retro-dialog>

// ui/src/Common/Header/Header.tsx
/*
 * Copyright (c) 2022 Ford Motor Company
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { ReactNode } from 'react';
import darkLogoPath from 'Assets/icons/icon-72x72.png';
import lightLogoPath from 'Assets/icons/icon-light-72x72.png';
import { getThemeClassFromUserSettings } from 'State/ThemeState';
import Theme from 'Types/Theme';

import './Header.scss';

interface Props {
	name: string;
	children?: ReactNode;
}

function Header(props: Props) {
	const { name, children } = props;

	const retroquestLogo =
		getThemeClassFromUserSettings() === Theme.DARK
			? lightLogoPath
			: darkLogoPath;

	return (
		<header className="header">
			<div className="left-content">
				<a href="/" className="logo-link" data-testid="retroquestLogoLink">
					<img
						src={retroquestLogo}
						className="logo"
						title="RetroQuest"
						alt="Retro Quest"
					/>
				</a>
				<span className="horizontal-separator" />
				<h1 className="team-name">{name}</h1>
			</div>
			{children}
		</header>
	);
}

export default Header;
